#!/bin/bash
#
# mkinitcpio install for ShadowOS (Arch Linux)
# /etc/initcpio/install/shadow
#

build() {
    add_module dm_crypt
    add_module dm_mod
    add_module xts
    add_module aes_generic
    add_module sha256_generic
    add_module sha512_generic
    add_module serpent_generic
    add_module twofish_generic
    add_module vfat
    add_module usb_storage
    
    add_binary cryptsetup
    add_binary blkid
    
    add_runscript
}

help() {
    cat << 'HELPEOF'
This hook enables ShadowOS hidden partition boot.

Add 'shadowboot' to kernel cmdline to activate hidden boot.
The hook will:
  1. Find LUKS encrypted partition
  2. Search for detached header in .shadow/header.bin
  3. Prompt for password
  4. Decrypt and set as root

Usage in mkinitcpio.conf:
  HOOKS=(... shadow ...)

Kernel cmdline:
  linux /vmlinuz shadowboot quiet
HELPEOF
}
